// <auto-generated />
using Asset_Tracking_Databased;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asset_Tracking_Databased.Migrations
{
    [DbContext(typeof(DemoDBContext))]
    partial class DemoDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Asset_Tracking_Databased.Office", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficePlace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Currency = "EUR",
                            OfficePlace = "Spain"
                        },
                        new
                        {
                            ID = 2,
                            Currency = "SEK",
                            OfficePlace = "Sweden"
                        },
                        new
                        {
                            ID = 3,
                            Currency = "GBP",
                            OfficePlace = "United Kingdom"
                        });
                });

            modelBuilder.Entity("Asset_Tracking_Databased.Products", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfficeID")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeID")
                        .HasColumnType("int");

                    b.Property<float>("UKPrice")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("OfficeID");

                    b.HasIndex("ProductTypeID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Brand = "Acer",
                            Date = "2010-05-29",
                            Model = "Liquid Z900",
                            OfficeID = 2,
                            ProductTypeID = 2,
                            UKPrice = 120f
                        },
                        new
                        {
                            ID = 2,
                            Brand = "Acer",
                            Date = "2020-12-18",
                            Model = "Nitro 5",
                            OfficeID = 3,
                            ProductTypeID = 1,
                            UKPrice = 855f
                        },
                        new
                        {
                            ID = 3,
                            Brand = "Alienware",
                            Date = "2022-06-01",
                            Model = "AURORA RYZEN R10",
                            OfficeID = 1,
                            ProductTypeID = 3,
                            UKPrice = 1839f
                        },
                        new
                        {
                            ID = 4,
                            Brand = "HP",
                            Date = "2017-1-1",
                            Model = "Pavilion TP01",
                            OfficeID = 1,
                            ProductTypeID = 3,
                            UKPrice = 1100f
                        });
                });

            modelBuilder.Entity("Asset_Tracking_Databased.ProductType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            TypeName = "Laptops"
                        },
                        new
                        {
                            ID = 2,
                            TypeName = "Mobiles"
                        },
                        new
                        {
                            ID = 3,
                            TypeName = "Computers"
                        });
                });

            modelBuilder.Entity("Asset_Tracking_Databased.Products", b =>
                {
                    b.HasOne("Asset_Tracking_Databased.Office", "Office")
                        .WithMany("Products")
                        .HasForeignKey("OfficeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Asset_Tracking_Databased.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Asset_Tracking_Databased.Office", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Asset_Tracking_Databased.ProductType", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
